import {Gender, TodayPlanType} from '@modules/tenant/tenant.type';
import {ElapsedListSection} from './elapsed.type';

export const ELAPSED_DATA: ElapsedListSection[] = [
  {
    id: '0',
    title: 'ア行',
    data: [
      {
        tenantCode: 'tenant1',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        hasPreviousOvernightStay: true,
        goingOutPlans: [
          {
            id: 'tp1',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.Commute,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        elapsedRecords: [
          {
            id: 'elapsed1',
            recordDate: '2024-12-03T11:11:33',
            placeTemplate: '',
            placeKey: '',
            classification: 'ケアマネジャーの',
            reporter: 'ケアマネ',
            serviceType: '',
            registerPhoto: 'images',
            content:
              '発生現場の画像を添付しました発生現場の画像を添付しました【経過記録】ケアマネジャーの記録を表示する【経過記録】ケアマネジャーの記録を表示する【経過記録】ケアマネジャーの記録を表示する【経過記録】ケアマネジャーの記録を表示する',
            settingReport: '',
            isAssign: false,
            isSynced: false,
          },
          {
            id: 'elapsed2',
            recordDate: '2022-11-03T12:00:33',
            placeTemplate: '',
            placeKey: '',
            classification: '事故報告',
            reporter: '山下 達郎',
            serviceType: '',
            registerPhoto: 'images',
            content: '発生現場の画像を添付しました発生現場の画像を添付しました',
            settingReport: '１週間',
            isAssign: false,
            isSynced: true,
          },
        ],
      },
      {
        tenantCode: 'tenant2',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Male,
        hasNotice: false,
        goingOutPlans: [],
        elapsedRecords: [
          {
            id: 'elapsed3',
            recordDate: '2022-02-15T13:10:33',
            placeTemplate: '',
            placeKey: '',
            classification: '事故報告',
            reporter: '山下 達郎',
            serviceType: '',
            registerPhoto: '',
            content: '発生現場の画像を添付しました発生現場の画像を添付しました',
            settingReport: '１週間',
            isAssign: true,
            isSynced: true,
          },
          {
            id: 'elapsed4',
            recordDate: '2022-02-15T10:10:33',
            placeTemplate: '',
            placeKey: '',
            classification: '事故報告',
            reporter: '山下 達郎',
            serviceType: '',
            registerPhoto: '',
            content: '発生現場の画像を添付しました発生現場の画像を添付しました',
            settingReport: '１ヶ月',
            isAssign: false,
            isSynced: true,
          },
          {
            id: 'elapsed5',
            recordDate: '2022-08-15T23:10:33',
            placeTemplate: '',
            placeKey: '',
            classification: '事故報告',
            reporter: '山下 達郎',
            serviceType: '',
            registerPhoto: '',
            content: '発生現場の画像を添付しました発生現場の画像を添付しました',
            settingReport: '３日間',
            isAssign: false,
            isSynced: false,
          },
        ],
      },
      {
        tenantCode: 'tenant3',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        goingOutPlans: [
          {
            id: 'tp3',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.DayOuting,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        elapsedRecords: [
          {
            id: 'elapsed6',
            recordDate: '2022-02-15T13:10:33',
            placeTemplate: '',
            placeKey: '',
            classification: '事故報告',
            reporter: '山下 達郎',
            serviceType: '',
            registerPhoto: 'images',
            content: '発生現場の画像を添付しました発生現場の画像を添付しました',
            settingReport: '３日間',
            isAssign: true,
            isSynced: true,
          },
        ],
      },
    ],
  },
  {
    id: '1',
    title: '血圧',
    data: [
      {
        tenantCode: 'tenant4',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        goingOutPlans: [
          {
            id: 'tp4',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.OvernightOutingDateBack,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
          {
            id: 'tp5',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.OvernightOuting,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
          {
            id: 'tp6',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.OvernightOutingInProgress,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        elapsedRecords: [
          {
            id: 'elapsed7',
            recordDate: '2022-02-15T13:10:33',
            placeTemplate: '',
            placeKey: '',
            classification: '事故報告',
            reporter: '山下 達郎',
            serviceType: '',
            registerPhoto: '',
            content: '発生現場の画像を添付しました発生現場の画像を添付しました',
            settingReport: '',
            isAssign: false,
            isSynced: false,
          },
        ],
      },
      {
        tenantCode: 'tenant5',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Male,
        hasNotice: false,
        hasPreviousOvernightStay: true,
        goingOutPlans: [],
        elapsedRecords: [
          {
            id: 'elapsed14',
            recordDate: '2022-02-15T13:10:33',
            placeTemplate: '',
            placeKey: '',
            classification: '事故報告',
            reporter: '山下 達郎',
            serviceType: '',
            registerPhoto: '',
            content: '発生現場の画像を添付しました発生現場の画像を添付しました',
            settingReport: '１週間',
            isAssign: true,
            isSynced: true,
          },
          {
            id: 'elapsed15',
            recordDate: '2022-02-15T13:10:33',
            placeTemplate: '',
            placeKey: '',
            classification: '事故報告',
            reporter: '山下 達郎',
            serviceType: '',
            registerPhoto: '',
            content: '発生現場の画像を添付しました発生現場の画像を添付しました',
            settingReport: '１週間',
            isAssign: true,
            isSynced: true,
          },
        ],
      },
    ],
  },
  {
    id: '2',
    title: '出欠席',
    data: [
      {
        tenantCode: 'tenant6',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Male,
        hasNotice: true,
        goingOutPlans: [],
        elapsedRecords: [
          {
            id: 'elapsed13',
            recordDate: '2022-02-15T13:10:33',
            placeTemplate: '',
            placeKey: '',
            classification: '事故報告',
            reporter: '山下 達郎',
            serviceType: '',
            registerPhoto: '',
            content: '発生現場の画像を添付しました発生現場の画像を添付しました',
            settingReport: '１週間',
            isAssign: true,
            isSynced: true,
          },
        ],
        registerState: '提供中',
      },
      {
        tenantCode: 'tenant7',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: false,
        goingOutPlans: [
          {
            id: 'tp12',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.HavingVisitors,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        elapsedRecords: [],
      },
      {
        tenantCode: 'tenant8',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Male,
        hasNotice: false,
        goingOutPlans: [],
        elapsedRecords: [],
        registerState: '欠席',
      },
      {
        tenantCode: 'tenant9',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        goingOutPlans: [
          {
            id: 'tp11',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.OvernightOuting,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        elapsedRecords: [],
      },
      {
        tenantCode: 'tenant10',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        goingOutPlans: [
          {
            id: 'tp10',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.OvernightOutingDateOut,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        elapsedRecords: [],
      },
      {
        tenantCode: 'tenant11',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        goingOutPlans: [],
        elapsedRecords: [],
        registerState: '帰所',
      },
    ],
  },
];
