import {TRehaContentDetail} from '@molecules/RehaContentRow';

export const FAKE_REHA_DATAIL: TRehaContentDetail[] = [
  {
    practiceContent: 'ボールストレッチA',
    performStatus: '中止',
    time: '',
    category: 'ボールトレーニング・グルップ',
    target: {
      weight: '20',
      count: '5',
      time: '5',
    },
    perform: {
      weight: '100',
      count: '15',
      time: '95',
    },
    finishedLevel: '可',
    borgScale: '17:かなりきつい',
    memo: 'これはメモです。',
    reporter: '山下 達郎',
  },
  {
    practiceContent: 'ボールストレッチA',
    performStatus: '実施',
    time: '22:22 〜 22:22',
    category: 'ボールトレーニング・グルップ',
    target: {
      weight: '20',
      count: '5',
      time: '5',
    },
    perform: {
      weight: '100',
      count: '15',
      time: '95',
    },
    finishedLevel: '可',
    borgScale: '17:かなりきつい',
    memo: 'これはメモです。これはメモです。これはメモです。',
    reporter: '山下 達郎',
  },
  {
    practiceContent: 'ボールストレッチA',
    performStatus: '未実施',
    time: '',
    category: 'ボールトレーニング・グルップ',
    target: {
      weight: '20',
      count: '5',
      time: '5',
    },
    perform: {
      weight: '',
      count: '',
      time: '',
    },
    finishedLevel: '',
    borgScale: '',
    memo: '',
    reporter: '山下 達郎',
  },
  {
    practiceContent: 'ボールストレッチA',
    performStatus: '実施',
    time: '22:22 〜 23:02',
    category: 'ボールトレーニング・グルップ',
    target: {
      weight: '20',
      count: '5',
      time: '5',
    },
    perform: {
      weight: '100',
      count: '15',
      time: '95',
    },
    finishedLevel: '可',
    borgScale: '17:かなりきつい',
    memo: '',
    reporter: '山下 達郎',
  },
  {
    practiceContent: 'ボールストレッチA',
    performStatus: '中止',
    time: '',
    category: 'ボールトレーニング・グルップ',
    target: {
      weight: '20',
      count: '5',
      time: '5',
    },
    perform: {
      weight: '100',
      count: '15',
      time: '95',
    },
    finishedLevel: '可',
    borgScale: '17:かなりきつい',
    memo: 'これはメモです。これはメモです。これはメモです。これはメモです。これはメモです。これはメモです。す。これはメモです。す。これはメモです。す。これはメ',
    reporter: '山下 達郎',
  },
  {
    practiceContent: 'ボールストレッチA',
    performStatus: '実施',
    time: '22:22 〜 22:22',
    category: 'ボールトレーニング・グルップ',
    target: {
      weight: '20',
      count: '5',
      time: '5',
    },
    perform: {
      weight: '100',
      count: '15',
      time: '95',
    },
    finishedLevel: 'なし',
    borgScale: '17:かなりきつい',
    memo: 'これはメモです。これはメモです。これはメモです。これはメモです。これはメモです。これはメモです。す。これはメモです。す。これはメモです。す。これはメ',
    reporter: '山下 達郎',
  },
];
