import {userRecordVital} from '@modules/vital/vital.type';
import {RecordStatus} from '@molecules/PopoverRecordHeader';
import {Gender, TodayPlanType} from '@modules/tenant/tenant.type';
import {VitalListSection} from './vital.type';
import moment from 'moment';
import {DATE_TIME_FORMAT} from '@constants/constants';

const currentDate = new Date();
const yesterday = currentDate.setDate(currentDate.getDate() - 3);
const pastDay = currentDate.setDate(currentDate.getDate() - 10);

const yesterdayDate = moment(yesterday).format(DATE_TIME_FORMAT);
const pastDayDate = moment(pastDay).format(DATE_TIME_FORMAT);

export const dataVitalUser: userRecordVital = {
  name: 'Donal Trump',
  statusRecord: RecordStatus.UnSync,
  data: [
    {
      date: yesterdayDate,
      reporter: 'Ronaldo',
      pulse: '55',
      breathing: '25',
      highBloodPressure: '110',
      lowBloodPressure: '98',
      bodyTemperature: '37.5',
      oxygenSaturation: '99',
      weight: '55.0',
    },
    {
      date: pastDayDate,
      reporter: 'Messi',
      pulse: '66',
      breathing: '',
      highBloodPressure: '110',
      lowBloodPressure: '98',
      bodyTemperature: '37.5',
      oxygenSaturation: '99',
      weight: '55.0',
    },
  ],
};

export const VITAL_DATA_SECTIONS: VitalListSection[] = [
  {
    id: '0',
    title: 'ア行',
    data: [
      {
        tenantCode: 'tenant1',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        hasPreviousOvernightStay: true,
        todayPlans: [
          {
            id: 'tp1',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.Commute,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
          {
            id: 'tp2',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.HasPreviousOvernightStay,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        vital: [
          {
            id: 'vital1',
            recordDate: '2024-12-03T11:11:33',
            pulse: '70',
            respiratory: '50',
            highBloodPressure: '80',
            lowBloodPressure: '99',
            temperature: '40',
            saturation: '99',
            weight: '70',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital2',
            recordDate: '2024-12-03T13:11:33',
            pulse: '100',
            respiratory: '',
            highBloodPressure: '100',
            lowBloodPressure: '',
            temperature: '',
            saturation: '20',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital3',
            recordDate: '2024-12-03T14:11:33',
            pulse: '100',
            respiratory: '90',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
        ],
      },
      {
        tenantCode: 'tenant2',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Male,
        hasNotice: true,
        todayPlans: [
          {
            id: 'tp1',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.OvernightOutingDateBack,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        vital: [
          {
            id: 'vital4',
            recordDate: '2024-12-03T18:52:13',
            pulse: '',
            respiratory: '',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: '入力は複数選択を初期イモ',
            isSynced: true,
          },
          {
            id: 'vital5',
            recordDate: '2024-12-03T18:52:13',
            pulse: '',
            respiratory: '',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: '',
            isSynced: true,
          },
        ],
      },
      {
        tenantCode: 'tenant3',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        todayPlans: [
          {
            id: 'tp1',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.OvernightOutingDateBack,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        vital: [
          {
            id: 'vital6',
            recordDate: '2024-12-03T18:52:13',
            pulse: '',
            respiratory: '',
            highBloodPressure: '',
            lowBloodPressure: '100',
            temperature: '',
            saturation: '50',
            weight: '',
            memo: '',
            isSynced: true,
          },
          {
            id: 'vital7',
            recordDate: '2024-12-03T18:52:13',
            pulse: '',
            respiratory: '',
            highBloodPressure: '',
            lowBloodPressure: '100',
            temperature: '',
            saturation: '',
            weight: '',
            memo: '',
            isSynced: true,
          },
        ],
      },
    ],
  },
  {
    id: '1',
    title: 'ア行',
    data: [
      {
        tenantCode: 'tenant1',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        hasPreviousOvernightStay: true,
        todayPlans: [
          {
            id: 'tp1',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.Commute,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
          {
            id: 'tp2',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.HasPreviousOvernightStay,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        vital: [
          {
            id: 'vital1',
            recordDate: '2024-12-03T11:11:33',
            pulse: '70',
            respiratory: '50',
            highBloodPressure: '80',
            lowBloodPressure: '99',
            temperature: '40',
            saturation: '99',
            weight: '70',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital2',
            recordDate: '2024-12-03T13:11:33',
            pulse: '100',
            respiratory: '',
            highBloodPressure: '100',
            lowBloodPressure: '',
            temperature: '',
            saturation: '20',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital3',
            recordDate: '2024-12-03T14:11:33',
            pulse: '100',
            respiratory: '90',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
        ],
      },
      {
        tenantCode: 'tenant2',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Male,
        hasNotice: true,
        todayPlans: [
          {
            id: 'tp1',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.OvernightOutingDateBack,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        vital: [
          {
            id: 'vital4',
            recordDate: '2024-12-03T18:52:13',
            pulse: '',
            respiratory: '',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: '入力は複数選択を初期イモ',
            isSynced: true,
          },
          {
            id: 'vital5',
            recordDate: '2024-12-03T18:52:13',
            pulse: '',
            respiratory: '',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: '',
            isSynced: true,
          },
        ],
      },
    ],
  },
  {
    id: '2',
    title: 'ア行',
    data: [
      {
        tenantCode: 'tenant1',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        hasPreviousOvernightStay: true,
        todayPlans: [
          {
            id: 'tp1',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.Commute,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
          {
            id: 'tp2',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.HasPreviousOvernightStay,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        vital: [
          {
            id: 'vital1',
            recordDate: '2024-12-03T11:11:33',
            pulse: '70',
            respiratory: '50',
            highBloodPressure: '80',
            lowBloodPressure: '99',
            temperature: '40',
            saturation: '99',
            weight: '70',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital2',
            recordDate: '2024-12-03T13:11:33',
            pulse: '100',
            respiratory: '',
            highBloodPressure: '100',
            lowBloodPressure: '',
            temperature: '',
            saturation: '20',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital3',
            recordDate: '2024-12-03T14:11:33',
            pulse: '100',
            respiratory: '90',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
        ],
      },
    ],
  },
  {
    id: '3',
    title: 'ア行',
    data: [
      {
        tenantCode: 'tenant1',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        hasPreviousOvernightStay: false,
        todayPlans: [],
        vital: [
          {
            id: 'vital1',
            recordDate: '2024-12-03T11:11:33',
            pulse: '70',
            respiratory: '50',
            highBloodPressure: '80',
            lowBloodPressure: '',
            temperature: '40',
            saturation: '',
            weight: '',
            memo: '',
            isSynced: false,
          },
        ],
      },
      {
        tenantCode: 'tenant2',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        hasPreviousOvernightStay: true,
        todayPlans: [],
        vital: [
          {
            id: 'vital1',
            recordDate: '2024-12-03T11:11:33',
            pulse: '',
            respiratory: '',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: '',
            isSynced: false,
          },
        ],
      },
      {
        tenantCode: 'tenant3',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        hasPreviousOvernightStay: true,
        todayPlans: [],
        vital: [
          {
            id: 'vital1',
            recordDate: '2024-12-03T11:11:33',
            pulse: '',
            respiratory: '',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '99',
            weight: '70',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
        ],
      },
      {
        tenantCode: 'tenant4',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        hasPreviousOvernightStay: true,
        todayPlans: [
          {
            id: 'tp1',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.Commute,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
          {
            id: 'tp2',
            startDate: '',
            endDate: '',
            planType: TodayPlanType.HasPreviousOvernightStay,
            isConfirmedStart: false,
            isConfirmedEnd: true,
            place: '',
            comment: '',
            reporterName: '',
            reportDate: '',
          },
        ],
        vital: [
          {
            id: 'vital1',
            recordDate: '2024-12-03T11:11:33',
            pulse: '70',
            respiratory: '50',
            highBloodPressure: '80',
            lowBloodPressure: '99',
            temperature: '40',
            saturation: '99',
            weight: '70',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital2',
            recordDate: '2024-12-03T13:11:33',
            pulse: '100',
            respiratory: '',
            highBloodPressure: '100',
            lowBloodPressure: '',
            temperature: '',
            saturation: '20',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital3',
            recordDate: '2024-12-03T14:11:33',
            pulse: '100',
            respiratory: '90',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
        ],
      },
      {
        tenantCode: 'tenant5',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        hasPreviousOvernightStay: true,
        todayPlans: [],
        vital: [
          {
            id: 'vital1',
            recordDate: '2024-12-03T11:11:33',
            pulse: '70',
            respiratory: '50',
            highBloodPressure: '80',
            lowBloodPressure: '99',
            temperature: '40',
            saturation: '99',
            weight: '70',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital2',
            recordDate: '2024-12-03T13:11:33',
            pulse: '100',
            respiratory: '',
            highBloodPressure: '100',
            lowBloodPressure: '',
            temperature: '',
            saturation: '20',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital3',
            recordDate: '2024-12-03T14:11:33',
            pulse: '100',
            respiratory: '90',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
        ],
      },
      {
        tenantCode: 'tenant6',
        photoPath: '',
        firstNameFurigana: 'イモリ',
        surnameFurigana: 'ヒルコ',
        firstNameKanji: '井守',
        surnameKanji: '宏子',
        gender: Gender.Female,
        hasNotice: true,
        hasPreviousOvernightStay: true,
        todayPlans: [],
        vital: [
          {
            id: 'vital1',
            recordDate: '2024-12-03T11:11:33',
            pulse: '70',
            respiratory: '50',
            highBloodPressure: '80',
            lowBloodPressure: '99',
            temperature: '40',
            saturation: '99',
            weight: '70',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital2',
            recordDate: '2024-12-03T13:11:33',
            pulse: '100',
            respiratory: '',
            highBloodPressure: '100',
            lowBloodPressure: '',
            temperature: '',
            saturation: '20',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
          {
            id: 'vital3',
            recordDate: '2024-12-03T14:11:33',
            pulse: '100',
            respiratory: '90',
            highBloodPressure: '',
            lowBloodPressure: '',
            temperature: '',
            saturation: '',
            weight: '',
            memo: 'テンプレート入力は複数選択を初期ート入力は数選択を初期値とする',
            isSynced: false,
          },
        ],
      },
    ],
  },
];
